apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: helloworld-nodejs
  template:
    metadata:
      labels:
        app: helloworld-nodejs
        istio-injection: enabled
    spec:
      containers:
      - name: webapp
        image: ghcr.io/ciftcicagatay/helloworld-nodejs/helloworld-nodejs:sha-13862379182389638b228cdf3ab4bbedfd726279
        ports:
        - containerPort: 11130