apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: helloworld-nodejs
spec:
  selector:
    app: helloworld-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11130
      name: web
  type: LoadBalancer