apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: helloworld-nodejs
spec:
  selector:
    app: helloworld-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer